[package]
name = "bevy_scene_hot_reloading"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", default-features = false, features = ["bevy_scene"] }

[features]
default = ["log"]
log = ["bevy/bevy_log"]
